apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-application-config
  annotations:
    kapp.k14s.io/versioned: ""
data:
  application.yml: |
    spring:
      cloud:
        gateway:
          routes:
          - id: simple_get
            uri: http://httpbin.org:80
            predicates:
            - Path=/httpbin/**
            filters:
            - RewritePath=/httpbin/?(?<segment>.*), /$\{segment}
          - id: circuit_breaker
            uri: http://httpbin.org:80
            predicates:
            - Path=/httpbincb/**
            filters:
            - RewritePath=/httpbincb/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: circuitBreaker
                fallbackUri: forward:/inCaseOfFailureUseThis
          - id: fallback
            uri: http://httpbin.org:80
            predicates:
            - Path=/inCaseOfFailureUseThis
            filters:
            - RewritePath=/.*, /status/204
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: harbor.eqix.vmwedge.com/api-gateway/api-gateway:latest
        name: api-gateway
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          failureThreshold: 5
          periodSeconds: 2
          initialDelaySeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /workspace/config
      volumes:
      - name: config-volume
        configMap:
          name: spring-application-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: api-gateway
spec:
  virtualhost:
    fqdn: gateway.apps.eqix.vmwedge.com
  routes:
  - services:
    - name: api-gateway
      port: 8080
