apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-build-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: api-gateway
spec:
  builder:
    kind: ClusterBuilder
    name: default
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  cache:
    volume:
      persistentVolumeClaimName: api-gateway-build-cache
  source:
    git:
      revision: main
      url: https://github.com/cdelashmutt-pivotal/api-gateway
  tag: harbor.eqix.vmwedge.com/api-gateway/api-gateway

